export const userColumns = [
  { field: 'centroid_x', headerName: 'centroid_x', width: 200 },
  { field: 'centroid_y', headerName: 'centroid_y', width: 200 },
  { field: 'centroid_z', headerName: 'centroid_z', width: 100 },
  { field: 'dim_x', headerName: 'dim_x', width: 100 },
  { field: 'dim_y', headerName: 'dim_y', width: 100 },
  { field: 'dim_z', headerName: 'dim_z', width: 100 },
  { field: 'volume', headerName: 'volume', width: 100 },
  { field: 'topo', headerName: 'topo', width: 100 },
  { field: 'cu', headerName: 'cu', width: 100 },
  { field: 'rec', headerName: 'rec', width: 100 },
  { field: 'au', headerName: 'au', width: 100 },
  { field: 'densidad', headerName: 'densidad', width: 100 },
  { field: 'categ', headerName: 'categ', width: 100 },
  { field: 'material', headerName: 'material', width: 100 },
  { field: 'pit_lg', headerName: 'pit_lg', width: 100 },
  // { field: "mined_1", headerName: "mined_1", width: 100 },
  // { field: "mined_2", headerName: "mined_2", width: 100 },
  // { field: "mined_3", headerName: "mined_3", width: 100 },
  // { field: "mined_4", headerName: "mined_4", width: 100 },
  // { field: "mined_5", headerName: "mined_5", width: 100 },
  // { field: "mined_6", headerName: "mined_6", width: 100 },
  // { field: "mined_7", headerName: "mined_7", width: 100 },
  // { field: "mined_8", headerName: "mined_8", width: 100 },
  // { field: "mined_9", headerName: "mined_9", width: 100 },
  // { field: "mined_10", headerName: "mined_10", width: 100 },
  // { field: "mined_11", headerName: "mined_11", width: 100 },
  // { field: "mined_12", headerName: "mined_12", width: 100 },
  // { field: "period", headerName: "period", width: 100 },
  // { field: "product", headerName: "product", width: 100 },
  // { field: "cutoiff2", headerName: "cutoiff2", width: 100 },
  // { field: "sequence", headerName: "sequence", width: 100 },
  // { field: "stp_anim_seq", headerName: "stp_anim_seq", width: 100 },
  // { field: "pit_op", headerName: "pit_op", width: 100 },
  // { field: "phase_pit8", headerName: "phase_pit8", width: 100 },
  // { field: "pit_op2", headerName: "pit_op2", width: 100 },
  // { field: "pit_op3", headerName: "pit_op3", width: 100 },
  // { field: "prod_waste", headerName: "prod_waste", width: 100 },
  // { field: "trial", headerName: "trial", width: 100 },
  // { field: "trial_optim", headerName: "trial_optim", width: 100 },
  // { field: "trial_phase", headerName: "trial_phase", width: 100 },
]
